// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TCC/TCCWS/unip-domain/src/main/resources/proto/keepAlive.proto

package br.unip.tcc.proto;

public final class KeepAliveProto {
  private KeepAliveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EquipmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code br.unip.tcc.proto.Equipment}
   */
  public static final class Equipment extends
      com.google.protobuf.GeneratedMessage
      implements EquipmentOrBuilder {
    // Use Equipment.newBuilder() to construct.
    private Equipment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Equipment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Equipment defaultInstance;
    public static Equipment getDefaultInstance() {
      return defaultInstance;
    }

    public Equipment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Equipment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Equipment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Equipment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.unip.tcc.proto.KeepAliveProto.Equipment.class, br.unip.tcc.proto.KeepAliveProto.Equipment.Builder.class);
    }

    public static com.google.protobuf.Parser<Equipment> PARSER =
        new com.google.protobuf.AbstractParser<Equipment>() {
      public Equipment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Equipment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Equipment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Equipment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.unip.tcc.proto.KeepAliveProto.Equipment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.unip.tcc.proto.Equipment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Equipment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Equipment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.unip.tcc.proto.KeepAliveProto.Equipment.class, br.unip.tcc.proto.KeepAliveProto.Equipment.Builder.class);
      }

      // Construct using br.unip.tcc.proto.KeepAliveProto.Equipment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Equipment_descriptor;
      }

      public br.unip.tcc.proto.KeepAliveProto.Equipment getDefaultInstanceForType() {
        return br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance();
      }

      public br.unip.tcc.proto.KeepAliveProto.Equipment build() {
        br.unip.tcc.proto.KeepAliveProto.Equipment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.unip.tcc.proto.KeepAliveProto.Equipment buildPartial() {
        br.unip.tcc.proto.KeepAliveProto.Equipment result = new br.unip.tcc.proto.KeepAliveProto.Equipment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.unip.tcc.proto.KeepAliveProto.Equipment) {
          return mergeFrom((br.unip.tcc.proto.KeepAliveProto.Equipment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.unip.tcc.proto.KeepAliveProto.Equipment other) {
        if (other == br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.unip.tcc.proto.KeepAliveProto.Equipment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.unip.tcc.proto.KeepAliveProto.Equipment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:br.unip.tcc.proto.Equipment)
    }

    static {
      defaultInstance = new Equipment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:br.unip.tcc.proto.Equipment)
  }

  public interface CurrentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float a = 1;
    /**
     * <code>required float a = 1;</code>
     */
    boolean hasA();
    /**
     * <code>required float a = 1;</code>
     */
    float getA();

    // required float b = 2;
    /**
     * <code>required float b = 2;</code>
     */
    boolean hasB();
    /**
     * <code>required float b = 2;</code>
     */
    float getB();

    // required float c = 3;
    /**
     * <code>required float c = 3;</code>
     */
    boolean hasC();
    /**
     * <code>required float c = 3;</code>
     */
    float getC();
  }
  /**
   * Protobuf type {@code br.unip.tcc.proto.Current}
   */
  public static final class Current extends
      com.google.protobuf.GeneratedMessage
      implements CurrentOrBuilder {
    // Use Current.newBuilder() to construct.
    private Current(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Current(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Current defaultInstance;
    public static Current getDefaultInstance() {
      return defaultInstance;
    }

    public Current getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Current(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              a_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              b_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              c_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Current_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Current_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.unip.tcc.proto.KeepAliveProto.Current.class, br.unip.tcc.proto.KeepAliveProto.Current.Builder.class);
    }

    public static com.google.protobuf.Parser<Current> PARSER =
        new com.google.protobuf.AbstractParser<Current>() {
      public Current parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Current(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Current> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required float a = 1;
    public static final int A_FIELD_NUMBER = 1;
    private float a_;
    /**
     * <code>required float a = 1;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float a = 1;</code>
     */
    public float getA() {
      return a_;
    }

    // required float b = 2;
    public static final int B_FIELD_NUMBER = 2;
    private float b_;
    /**
     * <code>required float b = 2;</code>
     */
    public boolean hasB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float b = 2;</code>
     */
    public float getB() {
      return b_;
    }

    // required float c = 3;
    public static final int C_FIELD_NUMBER = 3;
    private float c_;
    /**
     * <code>required float c = 3;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float c = 3;</code>
     */
    public float getC() {
      return c_;
    }

    private void initFields() {
      a_ = 0F;
      b_ = 0F;
      c_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, a_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, b_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, c_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, a_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, b_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, c_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Current parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.unip.tcc.proto.KeepAliveProto.Current prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.unip.tcc.proto.Current}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Current_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Current_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.unip.tcc.proto.KeepAliveProto.Current.class, br.unip.tcc.proto.KeepAliveProto.Current.Builder.class);
      }

      // Construct using br.unip.tcc.proto.KeepAliveProto.Current.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        a_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        b_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Current_descriptor;
      }

      public br.unip.tcc.proto.KeepAliveProto.Current getDefaultInstanceForType() {
        return br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance();
      }

      public br.unip.tcc.proto.KeepAliveProto.Current build() {
        br.unip.tcc.proto.KeepAliveProto.Current result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.unip.tcc.proto.KeepAliveProto.Current buildPartial() {
        br.unip.tcc.proto.KeepAliveProto.Current result = new br.unip.tcc.proto.KeepAliveProto.Current(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.b_ = b_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c_ = c_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.unip.tcc.proto.KeepAliveProto.Current) {
          return mergeFrom((br.unip.tcc.proto.KeepAliveProto.Current)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.unip.tcc.proto.KeepAliveProto.Current other) {
        if (other == br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        if (other.hasB()) {
          setB(other.getB());
        }
        if (other.hasC()) {
          setC(other.getC());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasA()) {
          
          return false;
        }
        if (!hasB()) {
          
          return false;
        }
        if (!hasC()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.unip.tcc.proto.KeepAliveProto.Current parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.unip.tcc.proto.KeepAliveProto.Current) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float a = 1;
      private float a_ ;
      /**
       * <code>required float a = 1;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float a = 1;</code>
       */
      public float getA() {
        return a_;
      }
      /**
       * <code>required float a = 1;</code>
       */
      public Builder setA(float value) {
        bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float a = 1;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0F;
        onChanged();
        return this;
      }

      // required float b = 2;
      private float b_ ;
      /**
       * <code>required float b = 2;</code>
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float b = 2;</code>
       */
      public float getB() {
        return b_;
      }
      /**
       * <code>required float b = 2;</code>
       */
      public Builder setB(float value) {
        bitField0_ |= 0x00000002;
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float b = 2;</code>
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = 0F;
        onChanged();
        return this;
      }

      // required float c = 3;
      private float c_ ;
      /**
       * <code>required float c = 3;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float c = 3;</code>
       */
      public float getC() {
        return c_;
      }
      /**
       * <code>required float c = 3;</code>
       */
      public Builder setC(float value) {
        bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float c = 3;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:br.unip.tcc.proto.Current)
    }

    static {
      defaultInstance = new Current(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:br.unip.tcc.proto.Current)
  }

  public interface VoltageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float ab = 1;
    /**
     * <code>required float ab = 1;</code>
     */
    boolean hasAb();
    /**
     * <code>required float ab = 1;</code>
     */
    float getAb();

    // required float bc = 2;
    /**
     * <code>required float bc = 2;</code>
     */
    boolean hasBc();
    /**
     * <code>required float bc = 2;</code>
     */
    float getBc();

    // required float ca = 3;
    /**
     * <code>required float ca = 3;</code>
     */
    boolean hasCa();
    /**
     * <code>required float ca = 3;</code>
     */
    float getCa();
  }
  /**
   * Protobuf type {@code br.unip.tcc.proto.Voltage}
   */
  public static final class Voltage extends
      com.google.protobuf.GeneratedMessage
      implements VoltageOrBuilder {
    // Use Voltage.newBuilder() to construct.
    private Voltage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Voltage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Voltage defaultInstance;
    public static Voltage getDefaultInstance() {
      return defaultInstance;
    }

    public Voltage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Voltage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              ab_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              bc_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              ca_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Voltage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Voltage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.unip.tcc.proto.KeepAliveProto.Voltage.class, br.unip.tcc.proto.KeepAliveProto.Voltage.Builder.class);
    }

    public static com.google.protobuf.Parser<Voltage> PARSER =
        new com.google.protobuf.AbstractParser<Voltage>() {
      public Voltage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Voltage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Voltage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required float ab = 1;
    public static final int AB_FIELD_NUMBER = 1;
    private float ab_;
    /**
     * <code>required float ab = 1;</code>
     */
    public boolean hasAb() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float ab = 1;</code>
     */
    public float getAb() {
      return ab_;
    }

    // required float bc = 2;
    public static final int BC_FIELD_NUMBER = 2;
    private float bc_;
    /**
     * <code>required float bc = 2;</code>
     */
    public boolean hasBc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float bc = 2;</code>
     */
    public float getBc() {
      return bc_;
    }

    // required float ca = 3;
    public static final int CA_FIELD_NUMBER = 3;
    private float ca_;
    /**
     * <code>required float ca = 3;</code>
     */
    public boolean hasCa() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float ca = 3;</code>
     */
    public float getCa() {
      return ca_;
    }

    private void initFields() {
      ab_ = 0F;
      bc_ = 0F;
      ca_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCa()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, ab_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, bc_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, ca_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, ab_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, bc_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, ca_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.Voltage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.unip.tcc.proto.KeepAliveProto.Voltage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.unip.tcc.proto.Voltage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Voltage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Voltage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.unip.tcc.proto.KeepAliveProto.Voltage.class, br.unip.tcc.proto.KeepAliveProto.Voltage.Builder.class);
      }

      // Construct using br.unip.tcc.proto.KeepAliveProto.Voltage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ab_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        bc_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        ca_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_Voltage_descriptor;
      }

      public br.unip.tcc.proto.KeepAliveProto.Voltage getDefaultInstanceForType() {
        return br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance();
      }

      public br.unip.tcc.proto.KeepAliveProto.Voltage build() {
        br.unip.tcc.proto.KeepAliveProto.Voltage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.unip.tcc.proto.KeepAliveProto.Voltage buildPartial() {
        br.unip.tcc.proto.KeepAliveProto.Voltage result = new br.unip.tcc.proto.KeepAliveProto.Voltage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ab_ = ab_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bc_ = bc_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ca_ = ca_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.unip.tcc.proto.KeepAliveProto.Voltage) {
          return mergeFrom((br.unip.tcc.proto.KeepAliveProto.Voltage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.unip.tcc.proto.KeepAliveProto.Voltage other) {
        if (other == br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance()) return this;
        if (other.hasAb()) {
          setAb(other.getAb());
        }
        if (other.hasBc()) {
          setBc(other.getBc());
        }
        if (other.hasCa()) {
          setCa(other.getCa());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAb()) {
          
          return false;
        }
        if (!hasBc()) {
          
          return false;
        }
        if (!hasCa()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.unip.tcc.proto.KeepAliveProto.Voltage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.unip.tcc.proto.KeepAliveProto.Voltage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float ab = 1;
      private float ab_ ;
      /**
       * <code>required float ab = 1;</code>
       */
      public boolean hasAb() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float ab = 1;</code>
       */
      public float getAb() {
        return ab_;
      }
      /**
       * <code>required float ab = 1;</code>
       */
      public Builder setAb(float value) {
        bitField0_ |= 0x00000001;
        ab_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ab = 1;</code>
       */
      public Builder clearAb() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ab_ = 0F;
        onChanged();
        return this;
      }

      // required float bc = 2;
      private float bc_ ;
      /**
       * <code>required float bc = 2;</code>
       */
      public boolean hasBc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float bc = 2;</code>
       */
      public float getBc() {
        return bc_;
      }
      /**
       * <code>required float bc = 2;</code>
       */
      public Builder setBc(float value) {
        bitField0_ |= 0x00000002;
        bc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float bc = 2;</code>
       */
      public Builder clearBc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bc_ = 0F;
        onChanged();
        return this;
      }

      // required float ca = 3;
      private float ca_ ;
      /**
       * <code>required float ca = 3;</code>
       */
      public boolean hasCa() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float ca = 3;</code>
       */
      public float getCa() {
        return ca_;
      }
      /**
       * <code>required float ca = 3;</code>
       */
      public Builder setCa(float value) {
        bitField0_ |= 0x00000004;
        ca_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ca = 3;</code>
       */
      public Builder clearCa() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ca_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:br.unip.tcc.proto.Voltage)
    }

    static {
      defaultInstance = new Voltage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:br.unip.tcc.proto.Voltage)
  }

  public interface KeepAliveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .br.unip.tcc.proto.Equipment equipment = 1;
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    boolean hasEquipment();
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.Equipment getEquipment();
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder getEquipmentOrBuilder();

    // required .br.unip.tcc.proto.Current current = 2;
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    boolean hasCurrent();
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.Current getCurrent();
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder getCurrentOrBuilder();

    // required .br.unip.tcc.proto.Voltage voltage = 3;
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    boolean hasVoltage();
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.Voltage getVoltage();
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder getVoltageOrBuilder();

    // required string type = 4;
    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code br.unip.tcc.proto.KeepAlive}
   */
  public static final class KeepAlive extends
      com.google.protobuf.GeneratedMessage
      implements KeepAliveOrBuilder {
    // Use KeepAlive.newBuilder() to construct.
    private KeepAlive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeepAlive(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeepAlive defaultInstance;
    public static KeepAlive getDefaultInstance() {
      return defaultInstance;
    }

    public KeepAlive getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeepAlive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              br.unip.tcc.proto.KeepAliveProto.Equipment.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = equipment_.toBuilder();
              }
              equipment_ = input.readMessage(br.unip.tcc.proto.KeepAliveProto.Equipment.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(equipment_);
                equipment_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              br.unip.tcc.proto.KeepAliveProto.Current.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = current_.toBuilder();
              }
              current_ = input.readMessage(br.unip.tcc.proto.KeepAliveProto.Current.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(current_);
                current_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              br.unip.tcc.proto.KeepAliveProto.Voltage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = voltage_.toBuilder();
              }
              voltage_ = input.readMessage(br.unip.tcc.proto.KeepAliveProto.Voltage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(voltage_);
                voltage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_KeepAlive_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_KeepAlive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.unip.tcc.proto.KeepAliveProto.KeepAlive.class, br.unip.tcc.proto.KeepAliveProto.KeepAlive.Builder.class);
    }

    public static com.google.protobuf.Parser<KeepAlive> PARSER =
        new com.google.protobuf.AbstractParser<KeepAlive>() {
      public KeepAlive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeepAlive(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAlive> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .br.unip.tcc.proto.Equipment equipment = 1;
    public static final int EQUIPMENT_FIELD_NUMBER = 1;
    private br.unip.tcc.proto.KeepAliveProto.Equipment equipment_;
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    public boolean hasEquipment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.Equipment getEquipment() {
      return equipment_;
    }
    /**
     * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder getEquipmentOrBuilder() {
      return equipment_;
    }

    // required .br.unip.tcc.proto.Current current = 2;
    public static final int CURRENT_FIELD_NUMBER = 2;
    private br.unip.tcc.proto.KeepAliveProto.Current current_;
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    public boolean hasCurrent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.Current getCurrent() {
      return current_;
    }
    /**
     * <code>required .br.unip.tcc.proto.Current current = 2;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder getCurrentOrBuilder() {
      return current_;
    }

    // required .br.unip.tcc.proto.Voltage voltage = 3;
    public static final int VOLTAGE_FIELD_NUMBER = 3;
    private br.unip.tcc.proto.KeepAliveProto.Voltage voltage_;
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    public boolean hasVoltage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.Voltage getVoltage() {
      return voltage_;
    }
    /**
     * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
     */
    public br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder getVoltageOrBuilder() {
      return voltage_;
    }

    // required string type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      equipment_ = br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance();
      current_ = br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance();
      voltage_ = br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance();
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEquipment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVoltage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEquipment().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCurrent().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getVoltage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, equipment_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, current_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, voltage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, equipment_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, current_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, voltage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.unip.tcc.proto.KeepAliveProto.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.unip.tcc.proto.KeepAliveProto.KeepAlive prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.unip.tcc.proto.KeepAlive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.unip.tcc.proto.KeepAliveProto.KeepAliveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_KeepAlive_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_KeepAlive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.unip.tcc.proto.KeepAliveProto.KeepAlive.class, br.unip.tcc.proto.KeepAliveProto.KeepAlive.Builder.class);
      }

      // Construct using br.unip.tcc.proto.KeepAliveProto.KeepAlive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEquipmentFieldBuilder();
          getCurrentFieldBuilder();
          getVoltageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (equipmentBuilder_ == null) {
          equipment_ = br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance();
        } else {
          equipmentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (currentBuilder_ == null) {
          current_ = br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance();
        } else {
          currentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (voltageBuilder_ == null) {
          voltage_ = br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance();
        } else {
          voltageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.unip.tcc.proto.KeepAliveProto.internal_static_br_unip_tcc_proto_KeepAlive_descriptor;
      }

      public br.unip.tcc.proto.KeepAliveProto.KeepAlive getDefaultInstanceForType() {
        return br.unip.tcc.proto.KeepAliveProto.KeepAlive.getDefaultInstance();
      }

      public br.unip.tcc.proto.KeepAliveProto.KeepAlive build() {
        br.unip.tcc.proto.KeepAliveProto.KeepAlive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.unip.tcc.proto.KeepAliveProto.KeepAlive buildPartial() {
        br.unip.tcc.proto.KeepAliveProto.KeepAlive result = new br.unip.tcc.proto.KeepAliveProto.KeepAlive(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (equipmentBuilder_ == null) {
          result.equipment_ = equipment_;
        } else {
          result.equipment_ = equipmentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (currentBuilder_ == null) {
          result.current_ = current_;
        } else {
          result.current_ = currentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (voltageBuilder_ == null) {
          result.voltage_ = voltage_;
        } else {
          result.voltage_ = voltageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.unip.tcc.proto.KeepAliveProto.KeepAlive) {
          return mergeFrom((br.unip.tcc.proto.KeepAliveProto.KeepAlive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.unip.tcc.proto.KeepAliveProto.KeepAlive other) {
        if (other == br.unip.tcc.proto.KeepAliveProto.KeepAlive.getDefaultInstance()) return this;
        if (other.hasEquipment()) {
          mergeEquipment(other.getEquipment());
        }
        if (other.hasCurrent()) {
          mergeCurrent(other.getCurrent());
        }
        if (other.hasVoltage()) {
          mergeVoltage(other.getVoltage());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEquipment()) {
          
          return false;
        }
        if (!hasCurrent()) {
          
          return false;
        }
        if (!hasVoltage()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!getEquipment().isInitialized()) {
          
          return false;
        }
        if (!getCurrent().isInitialized()) {
          
          return false;
        }
        if (!getVoltage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.unip.tcc.proto.KeepAliveProto.KeepAlive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.unip.tcc.proto.KeepAliveProto.KeepAlive) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .br.unip.tcc.proto.Equipment equipment = 1;
      private br.unip.tcc.proto.KeepAliveProto.Equipment equipment_ = br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Equipment, br.unip.tcc.proto.KeepAliveProto.Equipment.Builder, br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder> equipmentBuilder_;
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public boolean hasEquipment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Equipment getEquipment() {
        if (equipmentBuilder_ == null) {
          return equipment_;
        } else {
          return equipmentBuilder_.getMessage();
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public Builder setEquipment(br.unip.tcc.proto.KeepAliveProto.Equipment value) {
        if (equipmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          equipment_ = value;
          onChanged();
        } else {
          equipmentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public Builder setEquipment(
          br.unip.tcc.proto.KeepAliveProto.Equipment.Builder builderForValue) {
        if (equipmentBuilder_ == null) {
          equipment_ = builderForValue.build();
          onChanged();
        } else {
          equipmentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public Builder mergeEquipment(br.unip.tcc.proto.KeepAliveProto.Equipment value) {
        if (equipmentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              equipment_ != br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance()) {
            equipment_ =
              br.unip.tcc.proto.KeepAliveProto.Equipment.newBuilder(equipment_).mergeFrom(value).buildPartial();
          } else {
            equipment_ = value;
          }
          onChanged();
        } else {
          equipmentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public Builder clearEquipment() {
        if (equipmentBuilder_ == null) {
          equipment_ = br.unip.tcc.proto.KeepAliveProto.Equipment.getDefaultInstance();
          onChanged();
        } else {
          equipmentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Equipment.Builder getEquipmentBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEquipmentFieldBuilder().getBuilder();
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder getEquipmentOrBuilder() {
        if (equipmentBuilder_ != null) {
          return equipmentBuilder_.getMessageOrBuilder();
        } else {
          return equipment_;
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Equipment equipment = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Equipment, br.unip.tcc.proto.KeepAliveProto.Equipment.Builder, br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder> 
          getEquipmentFieldBuilder() {
        if (equipmentBuilder_ == null) {
          equipmentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.unip.tcc.proto.KeepAliveProto.Equipment, br.unip.tcc.proto.KeepAliveProto.Equipment.Builder, br.unip.tcc.proto.KeepAliveProto.EquipmentOrBuilder>(
                  equipment_,
                  getParentForChildren(),
                  isClean());
          equipment_ = null;
        }
        return equipmentBuilder_;
      }

      // required .br.unip.tcc.proto.Current current = 2;
      private br.unip.tcc.proto.KeepAliveProto.Current current_ = br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Current, br.unip.tcc.proto.KeepAliveProto.Current.Builder, br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder> currentBuilder_;
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public boolean hasCurrent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Current getCurrent() {
        if (currentBuilder_ == null) {
          return current_;
        } else {
          return currentBuilder_.getMessage();
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public Builder setCurrent(br.unip.tcc.proto.KeepAliveProto.Current value) {
        if (currentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          current_ = value;
          onChanged();
        } else {
          currentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public Builder setCurrent(
          br.unip.tcc.proto.KeepAliveProto.Current.Builder builderForValue) {
        if (currentBuilder_ == null) {
          current_ = builderForValue.build();
          onChanged();
        } else {
          currentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public Builder mergeCurrent(br.unip.tcc.proto.KeepAliveProto.Current value) {
        if (currentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              current_ != br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance()) {
            current_ =
              br.unip.tcc.proto.KeepAliveProto.Current.newBuilder(current_).mergeFrom(value).buildPartial();
          } else {
            current_ = value;
          }
          onChanged();
        } else {
          currentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public Builder clearCurrent() {
        if (currentBuilder_ == null) {
          current_ = br.unip.tcc.proto.KeepAliveProto.Current.getDefaultInstance();
          onChanged();
        } else {
          currentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Current.Builder getCurrentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCurrentFieldBuilder().getBuilder();
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder getCurrentOrBuilder() {
        if (currentBuilder_ != null) {
          return currentBuilder_.getMessageOrBuilder();
        } else {
          return current_;
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Current current = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Current, br.unip.tcc.proto.KeepAliveProto.Current.Builder, br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder> 
          getCurrentFieldBuilder() {
        if (currentBuilder_ == null) {
          currentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.unip.tcc.proto.KeepAliveProto.Current, br.unip.tcc.proto.KeepAliveProto.Current.Builder, br.unip.tcc.proto.KeepAliveProto.CurrentOrBuilder>(
                  current_,
                  getParentForChildren(),
                  isClean());
          current_ = null;
        }
        return currentBuilder_;
      }

      // required .br.unip.tcc.proto.Voltage voltage = 3;
      private br.unip.tcc.proto.KeepAliveProto.Voltage voltage_ = br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Voltage, br.unip.tcc.proto.KeepAliveProto.Voltage.Builder, br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder> voltageBuilder_;
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public boolean hasVoltage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Voltage getVoltage() {
        if (voltageBuilder_ == null) {
          return voltage_;
        } else {
          return voltageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public Builder setVoltage(br.unip.tcc.proto.KeepAliveProto.Voltage value) {
        if (voltageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          voltage_ = value;
          onChanged();
        } else {
          voltageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public Builder setVoltage(
          br.unip.tcc.proto.KeepAliveProto.Voltage.Builder builderForValue) {
        if (voltageBuilder_ == null) {
          voltage_ = builderForValue.build();
          onChanged();
        } else {
          voltageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public Builder mergeVoltage(br.unip.tcc.proto.KeepAliveProto.Voltage value) {
        if (voltageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              voltage_ != br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance()) {
            voltage_ =
              br.unip.tcc.proto.KeepAliveProto.Voltage.newBuilder(voltage_).mergeFrom(value).buildPartial();
          } else {
            voltage_ = value;
          }
          onChanged();
        } else {
          voltageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public Builder clearVoltage() {
        if (voltageBuilder_ == null) {
          voltage_ = br.unip.tcc.proto.KeepAliveProto.Voltage.getDefaultInstance();
          onChanged();
        } else {
          voltageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.Voltage.Builder getVoltageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVoltageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      public br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder getVoltageOrBuilder() {
        if (voltageBuilder_ != null) {
          return voltageBuilder_.getMessageOrBuilder();
        } else {
          return voltage_;
        }
      }
      /**
       * <code>required .br.unip.tcc.proto.Voltage voltage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.unip.tcc.proto.KeepAliveProto.Voltage, br.unip.tcc.proto.KeepAliveProto.Voltage.Builder, br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder> 
          getVoltageFieldBuilder() {
        if (voltageBuilder_ == null) {
          voltageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.unip.tcc.proto.KeepAliveProto.Voltage, br.unip.tcc.proto.KeepAliveProto.Voltage.Builder, br.unip.tcc.proto.KeepAliveProto.VoltageOrBuilder>(
                  voltage_,
                  getParentForChildren(),
                  isClean());
          voltage_ = null;
        }
        return voltageBuilder_;
      }

      // required string type = 4;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:br.unip.tcc.proto.KeepAlive)
    }

    static {
      defaultInstance = new KeepAlive(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:br.unip.tcc.proto.KeepAlive)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_unip_tcc_proto_Equipment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_unip_tcc_proto_Equipment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_unip_tcc_proto_Current_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_unip_tcc_proto_Current_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_unip_tcc_proto_Voltage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_unip_tcc_proto_Voltage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_unip_tcc_proto_KeepAlive_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_unip_tcc_proto_KeepAlive_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>TCC/TCCWS/unip-domain/src/main/resourc" +
      "es/proto/keepAlive.proto\022\021br.unip.tcc.pr" +
      "oto\"\027\n\tEquipment\022\n\n\002id\030\001 \002(\005\"*\n\007Current\022" +
      "\t\n\001a\030\001 \002(\002\022\t\n\001b\030\002 \002(\002\022\t\n\001c\030\003 \002(\002\"-\n\007Volt" +
      "age\022\n\n\002ab\030\001 \002(\002\022\n\n\002bc\030\002 \002(\002\022\n\n\002ca\030\003 \002(\002\"" +
      "\244\001\n\tKeepAlive\022/\n\tequipment\030\001 \002(\0132\034.br.un" +
      "ip.tcc.proto.Equipment\022+\n\007current\030\002 \002(\0132" +
      "\032.br.unip.tcc.proto.Current\022+\n\007voltage\030\003" +
      " \002(\0132\032.br.unip.tcc.proto.Voltage\022\014\n\004type" +
      "\030\004 \002(\tB\020B\016KeepAliveProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_br_unip_tcc_proto_Equipment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_br_unip_tcc_proto_Equipment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_br_unip_tcc_proto_Equipment_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_br_unip_tcc_proto_Current_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_br_unip_tcc_proto_Current_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_br_unip_tcc_proto_Current_descriptor,
              new java.lang.String[] { "A", "B", "C", });
          internal_static_br_unip_tcc_proto_Voltage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_br_unip_tcc_proto_Voltage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_br_unip_tcc_proto_Voltage_descriptor,
              new java.lang.String[] { "Ab", "Bc", "Ca", });
          internal_static_br_unip_tcc_proto_KeepAlive_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_br_unip_tcc_proto_KeepAlive_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_br_unip_tcc_proto_KeepAlive_descriptor,
              new java.lang.String[] { "Equipment", "Current", "Voltage", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
