CREATE TABLE IF NOT EXISTS public.tcc_sysusergroup (
	sysusergroupid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	groupname varchar(255) NULL,
	CONSTRAINT tcc_sysusergroup_pkey PRIMARY KEY (sysusergroupid)
);
CREATE TABLE IF NOT EXISTS public.tcc_sysuser (
	sysuserid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"password" varchar(255) NULL,
	username varchar(255) NULL,
	sysusergroupid int8 NULL,
	CONSTRAINT tcc_sysuser_pkey PRIMARY KEY (sysuserid),
	CONSTRAINT fke989278fx8hxnf6gg4i1s4khv FOREIGN KEY (sysusergroupid) REFERENCES public.tcc_sysusergroup(sysusergroupid)
);

INSERT INTO tcc_sysusergroup (sysusergroupid,groupname) VALUES (1,'ADMIN');
INSERT INTO tcc_sysusergroup (sysusergroupid,groupname) VALUES (2,'OPERACAO');
INSERT INTO tcc_sysuser (sysuserid,password,username,sysusergroupid) VALUES (1,'$2a$10$YQRbjcneRPrqFA16HX4zV.2weS7ZDcJ4VqjXNZqS9Wvh.M1.6retq','Admin',1);

alter sequence tcc_sysuser_sysuserid_seq restart with 2;
alter sequence tcc_sysusergroup_sysusergroupid_seq restart with 3;
